name: Build and Release Plugin

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: macos-latest
    permissions:
      contents: write # Needed to create/update releases

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Install IINA
        run: brew install --cask iina

      - name: Install deps
        run: brew install curl grep aria2 ffmpeg git fzf yt-dlp

      - name: Add iina-plugin to PATH
        run: ln -s /Applications/IINA.app/Contents/MacOS/iina-plugin /usr/local/bin/iina-plugin

      - name: Build and Pack Plugin
        run: bun run pack # This runs build and then iina-plugin pack .

      - name: Create or Update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: ani-skip.iinaplgz # The file generated by 'bun run pack'
          prerelease: false
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
