name: Build and Release Plugin

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: macos-latest
    permissions:
      contents: write # Needed to create/update releases

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Tap IINA Homebrew repository
        run: brew tap iina/homebrew-mpv-iina

      - name: Install mpv-iina with HEAD flag
        run: brew install --HEAD iina/mpv-iina/mpv-iina

      - name: Create necessary directories
        run: |
          mkdir -p deps/include
          mkdir -p deps/lib

      - name: Copy header files
        run: |
          cp -R $(brew --prefix)/include/mpv deps/include/
          cp -R $(brew --prefix)/include/libavcodec deps/include/
          cp -R $(brew --prefix)/include/libavformat deps/include/
          cp -R $(brew --prefix)/include/libavutil deps/include/
          cp -R $(brew --prefix)/include/libswscale deps/include/

      - name: Run parse_doc.rb script
        run: |
          ruby other/parse_doc.rb
          cp other/MPVOption.swift iina/
          cp other/MPVCommand.swift iina/
          cp other/MPVProperty.swift iina/

      - name: Run change_lib_dependencies.rb script
        run: |
          ruby other/change_lib_dependencies.rb "$(brew --prefix)" "$(brew --prefix mpv-iina)/lib/libmpv.dylib"

      - name: Build and Pack Plugin
        run: bun run pack # This runs build and then iina-plugin pack .

      - name: Create or Update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: ani-skip.iinaplgz # The file generated by 'bun run pack'
          prerelease: false
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
